### ISSUE TITLE
Plugin Google Scholar failed

### ISSUE THREAD

**Issue by dylantuttle** [GevatterGaul/googlescholar-metadata#1]
calibre, version 2.5.0
ERROR: No matches found: <p>Failed to find any books that match your search. Try making the search <b>less specific</b>. For example, use only the author's last name and a single distinctive word from the title.<p>To see the full log, click Show Details.

Running identify query with parameters: 
{u'title': u'Dynamic assembly', u'timeout': 30, u'authors': [u'Farrell'], u'identifiers': {}} 
Using plugins: Google Scholar, Google, Amazon.com 
The log from individual plugins is below 

*****************************\* Google Scholar *****************************\* 
Request extra headers: [('User-agent', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3')] 
Found 0 results 
Downloading from Google Scholar took 0.0329999923706 
Plugin Google Scholar failed
Traceback (most recent call last):
  File "site-packages\calibre\ebooks\metadata\sources\identify.py", line 44, in run
  File "calibre_plugins.googlescholar_metadata.**init**", line 41, in identify
  File "site-packages\calibre\customize\zipplugin.py", line 179, in load_module
  File "calibre_plugins.googlescholar_metadata.config", line 10, in <module>
ImportError: No module named PyQt4 

---

*****************************\* Amazon.com *****************************\* 
Request extra headers: [('User-agent', 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:2.0.1) Gecko/20100101 Firefox/4.0.1')] 
Found 0 results 
Downloading from Amazon.com took 1.16199994087 
No matches found with query: u'http://www.amazon.com/s/?field-title=Dynamic+assembly&unfiltered=1&field-author=Farrell&search-alias=stripbooks&sort=relevanceexprank' 

---

*****************************\* Google *****************************\* 
Request extra headers: [('User-agent', 'Mozilla/5.0 (Windows NT 6.1; rv:6.0) Gecko/20110814 Firefox/6.0')] 
Found 0 results 
Downloading from Google took 0.371999979019 

---

The identify phase took 1.22 seconds 
The longest time (1.162000) was taken by: Amazon.com 
Merging results from different sources and finding earliest  publication dates from the worldcat.org service 
We have 0 merged results, merging took: 0.00 seconds

**Comment by GevatterGaul** [comment]
Why closed?

**Comment by dylantuttle** [comment]
I'm not using it. Would you like me to reopen?

**Comment by GevatterGaul** [comment]
Well, is the issue resolved?

**Comment by dylantuttle** [comment]
I removed the plugin, so I suppose it's resolved on my end.

**Comment by GevatterGaul** [comment]
I had no time to look after it yet, and I guess I won't in the near future. I will reopen it anyway.

**Comment by dylantuttle** [comment]
It's a good idea, but I ended up using Mendeley for journal articles.

**Comment by GevatterGaul** [comment]
I switched to Zotero, which is also the reason I didn't continue to develop this plugin.
